"""first

Revision ID: 4673dbc7b240
Revises: 
Create Date: 2019-02-01 16:49:44.914819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4673dbc7b240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('age_func',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['func_id'], ['function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=False),
    sa.Column('details', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('choicest', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('age_group_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sup_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_company.id'], ),
    sa.ForeignKeyConstraint(['sup_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('validate', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('banner')
    op.drop_table('supply_post')
    op.drop_table('book')
    op.drop_table('age_func')
    op.drop_table('supply')
    op.drop_table('post_company')
    op.drop_table('function')
    op.drop_table('age_group')
    # ### end Alembic commands ###
