"""unique add

Revision ID: a2800b4b44e6
Revises: 4673dbc7b240
Create Date: 2019-02-01 17:08:58.908973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2800b4b44e6'
down_revision = '4673dbc7b240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'age_group', ['name'])
    op.create_unique_constraint(None, 'banner', ['title'])
    op.create_unique_constraint(None, 'book', ['name'])
    op.create_unique_constraint(None, 'function', ['name'])
    op.create_unique_constraint(None, 'image', ['name'])
    op.create_unique_constraint(None, 'post_company', ['name'])
    op.create_unique_constraint(None, 'supply', ['name'])
    op.create_unique_constraint(None, 'supply', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supply', type_='unique')
    op.drop_constraint(None, 'supply', type_='unique')
    op.drop_constraint(None, 'post_company', type_='unique')
    op.drop_constraint(None, 'image', type_='unique')
    op.drop_constraint(None, 'function', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_constraint(None, 'banner', type_='unique')
    op.drop_constraint(None, 'age_group', type_='unique')
    # ### end Alembic commands ###
